title: Open Notes
email: alex.petrovortex@gmail.com
description: >
  Блог Саши Петрова.
url: "https://petrovortex.github.io"
permalink: /:title/
timezone: Europe/Moscow

plugins:
  - jekyll-seo-tag
  - jekyll-feed
