title: Open Thoughts
email: your-email@example.com
description: >
  Блог Саши Петрова.
url: "https://petrovortex.github.io"
permalink: /:title/
timezone: Europe/Moscow

plugins:
  - jekyll-seo-tag
  - jekyll-feed
