title: Open Thoughts
author: Sasha Petrov
email: alex.petrovortex@gmail.com
description: >
  Блог Саши Петрова. Мысли, идеи, заметки.

# Настройки для SEO
url: "https://petrovortex.github.io"
twitter_username: petrovortex
github_username:  petrovortex

# Настройки сборки
markdown: kramdown
permalink: /:year/:month/:day/:title/
plugins:
  - jekyll-seo-tag
  - jekyll-feed
